// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const whatIsIt: string;
export const whatIsItContainer: string;
export const whatIsItDescription: string;
export const whatIsItImage: string;
export const whatIsItTags: string;
