// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const useCaseContainer: string;
export const useCaseList: string;
export const useCaseItem: string;
