// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const investmentContainer: string;
export const investmentCard: string;
export const investmentRequired: string;
export const investmentExpenditure: string;
